### ISSUE TITLE
Loader does not show when project is build

### ISSUE THREAD

**Issue by FaizanMostafa** [AmurKhoyetsyan/react-js-loader#1]
Hi there, thanks for this wonderful package. I am encountering some strange behaviour by this package, I am using default spinner type in my project and it works just fine in development but as soon as i build the project with `npm run build` loader just disappears :(

**Comment by AmurikKhoyetsyan** [comment]
Hello! You need to enter the "build" folder, then run the command "npx serve".

**Comment by AmurikKhoyetsyan** [comment]
Also please make sure you put the package into dependencies not in devDependencies cause on live environment build will not consume devDependencies.

**Comment by FaizanMostafa** [comment]
@AmurKhoyetsyan Thanks for the reply but unfortunately none of your solutions worked :(

**Comment by AmurikKhoyetsyan** [comment]
@FaizanMostafa https://www.youtube.com/watch?v=ISjDsJ18WD4

**Comment by AmurikKhoyetsyan** [comment]
https://www.youtube.com/watch?v=ISjDsJ18WD4
