### ISSUE TITLE
it doesn't work for React 18.2.0

### ISSUE THREAD

**Issue by jcdesignweb** [AmurKhoyetsyan/react-js-loader#2]
After install the dependency and impor it in my code this says: ".**/myproject/node_modules/react-js-loader/index.d.ts' is not a module.ts(2306)**"

[
![Captura de pantalla de 2022-07-31 12-28-48](https://user-images.githubusercontent.com/5569930/182033726-ea1c1956-65f9-444b-a9d0-ab87942d8697.png)
](url)

**Comment by AmurikKhoyetsyan** [comment]
npm i react-js-loader@0.1.2

**Comment by AmurikKhoyetsyan** [comment]
npm i react-js-loader@0.1.2
or
npm i react-js-loader@0.1.3
